export const MODE = {
    DEFAULT: "DEFAULT",
    APPLY_SCHEMA: "APPLY_SCHEMA",
    APPLY_SCHEMA_EVERY: "APPLY_SCHEMA_EVERY",
    APPLY_SCHEMA_ONLY: "APPLY_SCHEMA_ONLY",
    APPLY_SWITCH: "APPLY_SWITCH",
    APPLY_SWITCH_EVERY: "APPLY_SWITCH_EVERY",
    REDUCE: "REDUCE",
  };